CREATE TABLE PRODUTOS
(CODPRODUTO INT IDENTITY,
NOME VARCHAR(50)NOT NULL,
PRECO VARCHAR(20)NOT NULL,
CONSTRAINT PK_CODPRODUTO PRIMARY KEY (CODPRODUTO));


CREATE TABLE CLIENTEVENDAS
(CODCLIENTE INT IDENTITY,
CODPROD INT,
DATA DATETIME NOT NULL,
CLIENTE VARCHAR (50),
QUANTIDADE INT NOT NULL,
CATEGORIA VARCHAR(20) NOT NULL,
PRECO NUMERIC(9,2)NOT NULL,
TOTAL NUMERIC(9,2)NOT NULL,
CONSTRAINT PK_CODCLIENTE PRIMARY KEY(CODCLIENTE),
CONSTRAINT FK_CODPROD FOREIGN KEY (CODPROD) REFERENCES PRODUTOS(CODPRODUTO));

CREATE TABLE COMPRAS
(CODCOMPRA INT IDENTITY,
DATA DATETIME,
QUANTIDADE INT NOT NULL,
DESCRICAO VARCHAR(50)NOT NULL,
PRECOUNIT NUMERIC(9,2)NOT NULL,
PRECOTOTAL NUMERIC(9,2)NOT NULL,
CONSTRAINT PK_VENDAS PRIMARY KEY(CODCOMPRA));


SELECT COUNT (QUANTIDADE) AS 'TOTAL' FROM CLIENTEVENDAS

SELECT SUM(TOTAL) AS'VENDAS' FROM CLIENTEVENDAS

SELECT SUM(PRECOTOTAL) AS'COMPRAS' FROM COMPRAS

SELECT * FROM CLIENTEVENDAS  INNER JOIN COMPRAS ON CLIENTEVENDAS.TOTAL = COMPRAS.PRECOTOTAL;


--TOTAL DE QUANTIDADE 30 DIAS 
SELECT COUNT (QUANTIDADE) AS 'TOTAL' FROM CLIENTEVENDAS   SELECT FORMAT(DATA, 'dd/MM/yyyy HH:mm:ss') from CLIENTEVENDAS where CAST(data as date) between CAST(DATEADD(day, -30,GETDATE()) as date)and cast(GETDATE() as date)

--TOTAL DE VENDAS POR 30 DIAS 
SELECT SUM(TOTAL) AS'VENDAS' FROM CLIENTEVENDAS  SELECT FORMAT(DATA, 'dd/MM/yyyy HH:mm:ss') from CLIENTEVENDAS where CAST(data as date) between CAST(DATEADD(day, -30,GETDATE()) as date)and cast(GETDATE() as date)

--TOTAL DE COMPRAS POR 30 DIAS 
SELECT SUM(PRECOTOTAL) AS'COMPRAS' FROM COMPRAS  SELECT FORMAT(DATA, 'dd/MM/yyyy HH:mm:ss') from COMPRAS where CAST(data as date) between CAST(DATEADD(day, -30,GETDATE()) as date)and cast(GETDATE() as date)